version: '3'
services:
  db:
    container_name: mood-broadcast_db
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=mood_broadcast
  app:
    build: .
    restart: always
    ports:
    - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=mood_broadcast
    depends_on:
    - db
