name: publish

on:
  push:
    branches:
    - main

jobs:
  publish-mood-broadcast-api-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx
        username: nologin
        password: ${{ secrets.SCW_SECRET_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx/mood-broadcast-api:latest
        docker push rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx/mood-broadcast-api:latest

