name: publish

on:
  push:
    branches:
    - main

jobs:
  publish-mood-broadcast-api-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v1
      with:
        registry: rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx
        username: nologin
        password: ${{ secrets.SCW_SECRET_TOKEN }}

    - name: Build the mood-broadcast-api Docker image
      env:
        DB_USER: ${{ secrets.SCW_DB_USER }}
        DB_PASSWORD: ${{ secrets.SCW_DB_PASSWORD }}
        DB_HOST: ${{ secrets.SCW_DB_HOST }}
        DB_NAME: ${{ secrets.SCW_DB_NAME }}
      run: |
        docker build . --build-arg DB_USER=$DB_USER --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_HOST=$DB_HOST --build-arg DB_NAME=$DB_NAME --tag rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx/mood-broadcast-api:latest
        docker push rg.fr-par.scw.cloud/funcscwmoodbroadcastjv8inonx/mood-broadcast-api:latest

